FROM amancevice/pandas:latest

LABEL \
  author="Viktor Ljungström" \
  description="Image with tools used for NF targeted seq analysis, python/pandas/click image" \
  maintainer="viktor.ljungstrom@igp.uu.se"


RUN \
  pip install click

CMD ["/bin/bash"]